apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: k8s-space
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:      
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/nginx
        - name: fluentbit
          image: fluent/fluent-bit:latest
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/nginx
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"            
            - name: FLUENT_ELASTICSEARCH_INDEX
              value: "nginx-logs"        
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
