apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: k8s-space
data:
  fluent-bit.conf: |
    [INPUT]
        name tail
        path /var/log/nginx/*.log
        read_from_head true
        parser nginx_access

    [FILTER]
        Name nest
        Match *
        Operation nest
        Wildcard *
        Nest_under log

    [OUTPUT]
        Name          es
        Match         *
        Host          ${FLUENT_ELASTICSEARCH_HOST}
        Port          ${FLUENT_ELASTICSEARCH_PORT}
        Index         ${FLUENT_ELASTICSEARCH_INDEX}
        Logstash_Format On        
